INSERT INTO SIGTASAD.DIVISION (DIVISION_NO,DIVISION_DESC,DIVISION_DESC_F,DIVISION_DESC_S) VALUES
	 (1,'GESTION','SERVICE GESTION','SERVICE GESTION'),
	 (2,'CONTROLE','SERVICE CONTROLE','SERVICE CONTROLE'),
	 (6,'ACCOUNTING','DIRECTION GÉNÉRALE','DIRECTION GÉNÉRALE'),
	 (7,'CASHING','SERVICE ACCUEIL INFORMATION','SERVICE ACCUEIL INFORMATION'),
	 (23,'INQUIRY/TAXROLL','ACCUEIL/IMMATRICULATION','ACCUEIL/IMMATRICULATION'),
	 (24,'ARCHIVES','CLASSEMENT','CLASSEMENT'),
	 (25,'ACTES','ACTES','ACTES'),
	 (26,'DATA ENTRY','SAISIE','SAISIE'),
	 (27,'REFUND','REMBOURSEMENT','REMBOURSEMENT'),
	 (28,'AUDIT','VÉRIFICATION','VÉRIFICATION');
INSERT INTO SIGTASAD.DIVISION (DIVISION_NO,DIVISION_DESC,DIVISION_DESC_F,DIVISION_DESC_S) VALUES
	 (29,'COLLECTION','SERVICE RECOUVREMENT','SERVICE RECOUVREMENT'),
	 (30,'CASHERING','CAISSE','CAISSE'),
	 (31,'IT','TECHNOLOGIES DE L''INFORMATION','TECHNOLOGIES DE L''INFORMATION'),
	 (32,'SECRETARIAT','SECRÉTARIAT','SECRÉTARIAT'),
	 (33,'DIRECTION DES GRANDES ENTREPRISES','DIRECTION DES GRANDES ENTREPRISES','DIRECTION DES GRANDES ENTREPRISES');