INSERT INTO SIGTASAD.DOC_COURRIER_ACTION (DOC_COURRIER_ACTION_NO,DOC_COURRIER_LIBELLE) VALUES
	 ('1','ENTREE DECOMPTE PJ COMPLEMENTAIRE'),
	 ('2','SORTIE DECOMPTE'),
	 ('3','ENTREE ENREGISTREMENT'),
	 ('4','SORTIE ENREGISTREMENT'),
	 ('5','SORTIE CNAVTO'),
	 ('6','SORTIE ATTESTATION IRSA'),
	 ('7','SORTIE CERTIFICATION');