INSERT INTO SIGTASAD.DOC_COURRIER_OBJECT (DOC_COURRIER_OBJECT_NO,DOC_COURRIER_OBJECT) VALUES
	 (1,'DEMANDE'),
	 (2,'LETTRE'),
	 (3,'CONTRAT'),
	 (4,'CONVENTION'),
	 (5,'ACTE'),
	 (6,'BAIL'),
	 (7,'PROCES-VERBAL'),
	 (8,'SORTANT');