INSERT INTO SIGTASAD.DOC_TYPE (DOC_TYPE_NO,DOC_TYPE_DESC,DOC_TYPE_DESC_F,DOC_TYPE_DESC_S,VALIDITY_PERIOD_MONTHS,TAX_TYPE_NO,IS_APPROVAL_DOC_FL,IS_IMP_BASE_DOC_FL,IS_CERTIF) VALUES
	 (84,'ATTEST ASS. NON ASS','ATTEST ASS. NON ASS',NULL,NULL,NULL,'N','N','N'),
	 (28,'TIN NOTIFICATION F.','ATTESTATION NIF',NULL,NULL,NULL,'N','Y','N'),
	 (1,'REMITTANCE','DECLARATION',NULL,NULL,NULL,'N','N','N'),
	 (2,'LETTER','LETTRE',NULL,1,NULL,'Y','N','N'),
	 (3,'OBJECTION','CONTENTIEUX',NULL,NULL,NULL,'N','N','N'),
	 (4,'ASSESSMENT','COTISATION',NULL,NULL,NULL,'N','N','N'),
	 (7,'INSTALLMENT LETTER','AVIS ACOMPTE PROV.',NULL,NULL,NULL,'N','N','N'),
	 (8,'ASSESSMENT NOTICE','AVIS DE COTISATION',NULL,NULL,NULL,'N','N','N'),
	 (9,'INSTALLMENT REMINDER','RAPPEL ACOMPTE PROV.',NULL,NULL,NULL,'N','N','N'),
	 (11,'REMINDER','RAPPEL',NULL,NULL,NULL,'N','N','N');
INSERT INTO SIGTASAD.DOC_TYPE (DOC_TYPE_NO,DOC_TYPE_DESC,DOC_TYPE_DESC_F,DOC_TYPE_DESC_S,VALIDITY_PERIOD_MONTHS,TAX_TYPE_NO,IS_APPROVAL_DOC_FL,IS_IMP_BASE_DOC_FL,IS_CERTIF) VALUES
	 (12,'ACCOUNT STATEMENT','ETAT DE COMPTE',NULL,2,NULL,'Y','Y','N'),
	 (13,'ARREARS DISTRIBUTION','DISTR./RESTES A RECV',NULL,NULL,NULL,'N','N','N'),
	 (14,'LATE  PAY.  REMINDER','RPPL RETARD PAIEMENT',NULL,NULL,NULL,'N','N','N'),
	 (15,'PAYMENT AGREEMENT','ENTENTE DE PAIEMENT',NULL,NULL,NULL,'N','N','N'),
	 (16,'AGENCY NOTICE',NULL,NULL,NULL,NULL,'N','N','N'),
	 (17,'PAY. AGREE. REMINDER','RPPL ENTENTE PAIEMEN',NULL,NULL,NULL,'N','N','N'),
	 (18,'AGENCY NOT. REMINDER',NULL,NULL,NULL,NULL,'Y','N','N'),
	 (19,'CORP. REG. FORM','FRM IMMATRICULATION',NULL,NULL,NULL,'N','N','N'),
	 (20,'EXEMPTION LETTER','DMDE EXONERATION',NULL,NULL,NULL,'Y','N','N'),
	 (91,'REASSESSMNT REQUEST','DMDE DE REDRESSEMNT',NULL,NULL,NULL,'N','N','N');
INSERT INTO SIGTASAD.DOC_TYPE (DOC_TYPE_NO,DOC_TYPE_DESC,DOC_TYPE_DESC_F,DOC_TYPE_DESC_S,VALIDITY_PERIOD_MONTHS,TAX_TYPE_NO,IS_APPROVAL_DOC_FL,IS_IMP_BASE_DOC_FL,IS_CERTIF) VALUES
	 (29,'ETAT FINANCIER','ETAT FINANCIER',NULL,NULL,NULL,'N','N','N'),
	 (30,'VAT CHANGE REGISTN',NULL,NULL,NULL,NULL,'N','N','N'),
	 (32,'REFUND REQUEST','DMDE REMBOURSEMENT',NULL,NULL,NULL,'N','N','N'),
	 (33,'PAYMENT RECEIPT','RECEPISSE CAISSE',NULL,NULL,NULL,'N','N','N'),
	 (73,'TAX CLEARANCE FORM',NULL,NULL,NULL,NULL,'N','N','N'),
	 (72,'DE-REGISTRATION RQST',NULL,NULL,NULL,NULL,'N','N','N'),
	 (74,'DOCUMENTED COMPLAINT','PLAINTE DOCUMENTEE',NULL,NULL,NULL,'N','N','N'),
	 (75,'WRITE-OFF REQUEST','DMDE DE RADIATION',NULL,NULL,NULL,'Y','N','N'),
	 (93,'COURRIER ADMINISTRATIF','COURRIER ADMINISTRATIF',NULL,NULL,NULL,'N','N','N'),
	 (94,'REQUE.ADMINIST.ACC ET INF','REQUE.ADMINIST.ACC ET INF',NULL,NULL,NULL,'N','N','N');
INSERT INTO SIGTASAD.DOC_TYPE (DOC_TYPE_NO,DOC_TYPE_DESC,DOC_TYPE_DESC_F,DOC_TYPE_DESC_S,VALIDITY_PERIOD_MONTHS,TAX_TYPE_NO,IS_APPROVAL_DOC_FL,IS_IMP_BASE_DOC_FL,IS_CERTIF) VALUES
	 (95,'REQUEST CONTRIBUABLE','REQUETE CONTRIBUABLE',NULL,NULL,NULL,'N','N','N'),
	 (79,'TAX CLEARANCE RQST',NULL,NULL,NULL,NULL,'N','N','N'),
	 (80,'AUDIT REPORT','RAPPORT DE VERIF',NULL,NULL,NULL,'N','N','N'),
	 (81,'REMITTANCE OLD','DECL.AVT.SIGTAS',NULL,NULL,NULL,'N','N','N'),
	 (34,'RQST FOR VAT QUITUS','DMDE QUITUS DE TVA',NULL,NULL,NULL,'N','N','Y'),
	 (97,'ADMIN.REQST.CONTROLE','REQUE.ADMINI.CONTROLE',NULL,NULL,NULL,'N','N','N'),
	 (98,'ADMIN.REQST.GESTION','REQU.ADMIN.GESTION',NULL,NULL,NULL,'N','N','N'),
	 (99,'ADMIN.REQST.DIREC','REQU.ADMIN.DIRECTION',NULL,NULL,NULL,'N','N','N'),
	 (82,'NOTIFICATION','ATTESTATION',NULL,NULL,NULL,'N','Y','N'),
	 (88,'ACTES','ACTES','ACTES',NULL,NULL,'Y','N','N');
INSERT INTO SIGTASAD.DOC_TYPE (DOC_TYPE_NO,DOC_TYPE_DESC,DOC_TYPE_DESC_F,DOC_TYPE_DESC_S,VALIDITY_PERIOD_MONTHS,TAX_TYPE_NO,IS_APPROVAL_DOC_FL,IS_IMP_BASE_DOC_FL,IS_CERTIF) VALUES
	 (90,'LIABILITY ERROR','ERR ASSUJETTISSEMNT',NULL,NULL,NULL,'Y','N','N'),
	 (89,'REFUND CHEQUE','CHEQUE REMBOURSEMENT',NULL,NULL,NULL,'Y','N','N'),
	 (92,'ATTEST. DE NON IMP.','ATTEST. DE NON IMP.
',NULL,NULL,NULL,'N','Y','N'),
	 (96,'REQU.ADMIN.RECOU','REQU.ADMIN.RECOU',NULL,NULL,NULL,'N','N','N'),
	 (100,'CONFIDENTIEL','CONFIDENTIEL',NULL,NULL,NULL,'N','N','N');