INSERT INTO SIGTASAD.FISCAL_REGIME (FISCAL_REGIME_NO,FISCAL_REGIME_DESC,FISCAL_REGIME_DESC_F,FISCAL_REGIME_DESC_S) VALUES
	 (1,'DROIT COMMUN','DROIT COMMUN','DC'),
	 (2,'ZONE FRANCHE','ZONE FRANCHE','ZF'),
	 (3,'CODE DES INVESTISSEURS','CODE DES INVESTISSEURS','CI'),
	 (4,'AUTRES','AUTRES','AUTRES'),
	 (5,'CONVENTION D''ETABLISSEMENT','CONVENTION D''ETABLISSEMENT','CE'),
	 (6,'LGIM','LGIM','LGIM');