INSERT INTO SIGTASAD.INACTIVE_TYPE (INACT_TYPE_NO,INACT_TYPE_DESC,INACT_TYPE_DESC_F,INACT_TYPE_DESC_S) VALUES
	 (4,'INACTIF','INACTIF','INACTIF'),
	 (2,'SUSPENDED','SUSPENSION','SUSPENSION'),
	 (1,'EXEMPTED','EXONERATION','EXONERATION'),
	 (3,'INDEF. SUSPENSION','INDEF. SUSPENSION','INDEF. SUSPENSION');