INSERT INTO SIGTASAD.SECTOR_ACTIVITY (SECTOR_ACT_NO,SECTOR_ACT_DESC,SECTOR_ACT_DESC_F,SECTOR_ACT_DESC_S) VALUES
	 (53,'INDUSTRIEL','INDUSTRIEL','INDUSTRIEL'),
	 (54,'TOURISTIQUE','TOURISTIQUE','TOURISTIQUE'),
	 (55,'COMMERCE','COMMERCE','COMMERCE'),
	 (56,'PRESTATION DE SERVICE','PRESTATION DE SERVICE','PRESTATION DE SERVICE'),
	 (57,'PECHERIE ELEVAGE','PECHERIE ELEVAGE','PECHERIE ELEVAGE'),
	 (58,'PETROLIER','PETROLIER','PETROLIER'),
	 (59,'MINE','MINE','MINE'),
	 (60,'TRANSPORT','TRANSPORT','TRANSPORT'),
	 (61,'BANQUE','BANQUE','BANQUE'),
	 (62,'ASSURANCE','ASSURANCE','ASSURANCE');
INSERT INTO SIGTASAD.SECTOR_ACTIVITY (SECTOR_ACT_NO,SECTOR_ACT_DESC,SECTOR_ACT_DESC_F,SECTOR_ACT_DESC_S) VALUES
	 (63,'HOTELLERIE','HOTELLERIE','HOTELLERIE'),
	 (64,'BATIMENT TRAVAUX PUBLICS','BATIMENT TRAVAUX PUBLICS','BATIMENT TRAVAUX PUBLICS'),
	 (65,'AGRICULTURE','AGRICULTURE','AGRICULTURE'),
	 (66,'TELECOMMUNICATION','TELECOMMUNICATION','TELECOMMUNICATION'),
	 (67,'IMMOBILIER','IMMOBILIER','IMMOBILIER'),
	 (68,'AMBASSADE','AMBASSADE','AMBASSADE'),
	 (69,'FINANCES','FINANCES','FINANCES'),
	 (70,'TABACS ET ALCOOL','TABACS ET ALCOOL','TABACS ET ALCOOL');