INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2567,'COLLECTE ET EXPORTATION DE CUIRS DE ZEBU-VENTE DE  VIANDE GROS ET DETAIL- IMPORTATION ET VENTE EN GROS ET DETAIL DE MARCHANDISES GENERALES '),
	 (1951,'IMPORT ET EXPORT DES MARCHANDISES GENERALES, ET CONSTRUCTION  - TRANSPORT '),
	 (1793,'EXPLOITATION INDUSTRIELLE ET COMMERCIALE - DES PLANTES AROMATIQUES - Exportateur - Importateur'),
	 (2066,'RECHERCHES PETROLIERES'),
	 (641,'CONFECTION D''ARTICLES D''HABILLEMENT - EXPORTATEUR'),
	 (2220,' Importation et revente des motos; des casques; des vetements sportifs; des pieces detachees pour motos, d''equipement materiels electroniques; atelier mecanique de reparation de motos'),
	 (2129,'PRESTATION DE SERVICE DANS LA DISTRIBUTION DE AIRTEL'),
	 (2709,'INSTITUTION FINANCIERE MUTUALISTE'),
	 (2352,'CONSTRUCTION GENERALE-IMPORTATION-EXPORTATION-NEGOCE-ET PLUS GENERALEMENT TOUTES OPERATIONS FINANCIERES, COMMERCIALES, IMMOBILIERES POUVANT SE RATTACHER DIRECTEMENT OU INDIRECTEMENT A L''OBJET SOCIAL OU OBJET CONNEXE QUI VIENT D''ETRE ENUMERE'),
	 (2272,'Centre d''appels, de traitement et de saisie, et de numerisation');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2294,'CONSTRUCTION, INSTALLATION, AMENAGEMENT ET LOCATION DE TOUT TYPE DE PLATEFORME, FIXE OU MOBILE, E USAGE DE JETEE PETROLIERE; TOUTE OPERATION MARITIME DE RECEPTION, DE CHARGEMENT ET DE DECHARGEMENT DES HYDROCARBURES QUELQUE SOIT LE TYPE DE NAVIRE, ET LE TRANSPORT D''HYDROCARBURES PAR PIPELINE VERS UN TERMINAL ET UN AUTRE HUB; GESTION EVENTUELLE PAR SOUS TRAITANCE OU EN DIRECT DE TOUT AMENAGEMENT ET OUTILLAGE APPARTENANT AU LOCATAIRE DE LA PLATEFORME.'),
	 (2317,'PLANTATION, COLLECTE, TRANSFORMATION, CONDITIONNEMENT ET EXPORTATION DE PRODUITS AGRICOLES. - PRODUCTION, ACHATS ET EXPORTATION DE PRODUITS ARTISANAUX.'),
	 (2348,'QUINCAILLERIE'),
	 (2590,'ACHAT, VENTE EN DETAIL, CONDITIONNEMENT, STOCKAGE, COURTAGE, REPRESENTATION, TRANSPORT, EXPORTATION ET COMMERCE DE TOUS PRODUITS, BIENS, MARCHANDISES ET NOTAMMENT : GIROFLES, VANILLES, EPICES, CAFE ET CACAO AINSI QUE DE LEUR SOUS PRODUITS. ACHAT OU PRISE EN BAIL EMPHYTEOTIQUE ET VENTE DE BIENS FONCIERS OU IMMOBILIERS, AINSI QUE LA CONSTRUCTION OU LA LOCATION DE BUREAUX, D''''USINES ET D''''ENTREPOTS. PARTICIPATION DE LA SOCIETE A TOUTES ENTREPRISES OU SOCIETES CREEES OU A CREER POUVANT SE RATTACHER DIRECTEMENT OU INDIRECTEMENT A L''''OBJET SOCIAL, AINSI QUE LA GESTION DE CES PARTICIPATIONS.'),
	 (2359,'ETUDE - REALISATION DE TOUS TRAVAUX DE CONSTRUCTION - PRESTATION DE CONSEIL ET D''ASSISTANCE - ACHAT - VENTE - LOCATION - IMPORTATION - EXPORTATION - APPAREILS ET OUTILLAGES D''ENTRETIEN DE TRAVAUX DE CONSTRUCTION '),
	 (2750,'activites d''''appui generalement dispense aux entreprises (gerante)'),
	 (2190,'ENTREPRISE GENERALE DE CONSTRUCTION, FOURNISSEUR: FOURNITURE DE BUREAU'),
	 (2887,'achats, ventes, production, transformation de produits vegetaux et de matieres premieres aromatiques -importation de produits aromatiques - vente des ces produits sur le marche local - achats de tous produits artisanaux ou de collecte - -	realisation d''etudes sur les produits sus cites - -exportation des produits sus cites - exploitation immobiliere - preparation et la collecte de vanille'),
	 (1284,'CONCEPTION, CONSTRUCTION ET DISTRIBUTION DE SOURCES D''ENERGIE ECOLOGIQUE. LA DISTRIBUTION DE CARBURANT ET GAZ'),
	 (2083,'IMPORTATEUR DE MARCHANDISES GENERALES
VENTE AU DETAIL DE MARCHANDISES GENERALES
MARCHAND FORAIN DE MARCHANDISES GENERALES ');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (223,'EXPLOITATION HOTELIERE ET TOURISTIQUE'),
	 (2723,'Commerce de combustible(carburants,lubrifiant)pour automobiles et gaz domestique,station essence!Vente de marchandises,btp,prestation de services,location de materiel!Location de voiture'),
	 (2113,'TOUTES ACTIVITES RELATIVES AUX CONSTRUCTIONS DANS LE DOMAINE DU BATIMENT, TRAVAUX PUBLICS, OUVRAGES D''ART'),
	 (2259,'Toutes fabrication de bonneterie pret a porter et l''''exportation des produits'),
	 (1103,'CONCEPTION, FABRICATION D''OBJETS, MEUBLES, REVETEMENT, DECORATION, PEINTURE, DORURE ET TOUS TRAVAUX DECORATIFS EN VUE DE LEUR EXPORTATION.'),
	 (1596,'EXECUTION DES TRAVAUX ROUTIERS, AMENAGEMENTS, CONSTRUCTIONS, REHABILITATION BATIMENTS'),
	 (1985,'ACHAT, IMPORTATION, VENTE DE  MARCHANDISES  GENERALES, QUINCAILLERIE, PIECES DETACHEES'),
	 (2642,'IMPORTATION ET GROSSISTE DE MARCHANDISES GENERALES - COLLECTE DE PRODUITS LOCAUX - EXPORTATION DE PIERRES INDUSTRIELLES, Importateur'),
	 (1735,'PRESTATION DE SERVICES AUX SOCIETES ET AUX PARTICULIERS ET LA CREATION, L''EXPLOITATION, LA GESTION DES SOCIETES COMMERCIALES, INDUSTRIELLES, LIBERALES, PROFESSIONNELLES, IMMOBILIERES OU FONCIERES'),
	 (1867,'COLLECTE , TRANSFORMATION, CULTURE ET COMMERCIALISATION DES PLANTES AROMATIQUES ET MEDICINALES - EXPORTATEUR');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (192,'COMMERCE EN GROS, DEMI-GROS, DETAIL DE MARCHANDISES GENERALES.PIECES DETACHEES ET PNEUMATIQUES, EXPORTATION, IMPORTATION'),
	 (617,' Import et vente d''accessoires textiles, marchandises generales en gros et au details, metiers, import et export, fabrication et vente d''articles divers(produits chimiques,plastiques,agricoles, alimentaires, produit en verre et matieres premieres)'),
	 (696,'PRESTATION DE SERVICE: GESTION DES SOCIETES'),
	 (96,'IMPORTATION ET VENTE MARCHANDISES GENERALES EN GROS ET EN DETAIL'),
	 (675,'INDUSTRIELLE (MALTERIE) ET AGRICULTURE'),
	 (291,'CONFECTIONS DES VETEMENTS - Exportateur - Importateur'),
	 (2144,'IMPORTATION DE MARCHANDISES GENERALES DIVERSES. DUTY FREE'),
	 (2789,'Importation et vente de marchandises generales en gros et detail'),
	 (2790,'COMMERCE D''EXPORTATION DES PRODUITS LOCAUX, VENTES EN GROS ET DETAIL DES MARCHANDISES GENERALES.'),
	 (2365,'EXPORTATION DE PRODUITS LOCAUX-IMPORTATION ET VENTE DE MARCHANDISES GENERALES EN GROS ET DETAIL');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2888,'CONCESSIONNAIRE-GARAGISTE - Importateur'),
	 (2138,'DISTRIBUTEUR DES PRODUITS  TELMA'),
	 (2350,'IMPORTATION DE MARCHANDIDES GENERALES ET VENTES'),
	 (15,'INDUSTRIE DE RECHAPAGE'),
	 (2119,'REPRESENTATION
   DE CELLER 
BRUNNENBAU GMBH & CO.KG  :FORAGE, 
OPERATIONS ,EXPLORATION ET CONNEXES
 '),
	 (1219,'EXPORTATION DE PRODUITS LOCAUX-HUILES ESSENTIELLES '),
	 (2324,'IMPORTATION, VENTE DE MARCHANDISE GENERALES EN GROS ET AU DETAILS'),
	 (1694,'TOUTES OPERATIONS  D''ASSURANCES'),
	 (317,'ACQUISITION, VENTE, ADMINISTRATION, EXPLOITATION PAR BAIL, LOCATION OU AUTREMENT DE TERRAINS ET BIENS IMMOBILIERS'),
	 (1543,'IMPORTATION,DISTRIBUTION,FABRICATION,DESPRODUITS CHIMIQUES ET INDUSTRIEL');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2230,'LA VENTE D''EQUIPEMENTS MEDICAUX 
LA VENTE DE CONSOMMABLES MEDICAUX
LE SERVICE APRES-VENTE DE CES EQUIPEMENTS ET CONSOMMABLES'),
	 (1093,'SERVICES ET INGENIERIE INFORMATIQUE'),
	 (1422,'AGENCE DE VOYAGES-TOUR OPERATEUR-LOCATION DE VOITURES-GSA CORSAIR'),
	 (1534,'AGENCE MARITIME,  CONSIGNATION DE NAVIRE ET DE TRANSPORT TERRESTRE, COLLECTE DE FRET MARITIME, MANUTENTION, COURTAGE, CONSIGNATION DE NAVIRE ET DE MARCHANDISES, NEGOCE, ENTREPOSAGE ET DISTRIBUTION, TRANSIT, COMMUNICATION DE TRANSPORT, COMMISSION EN DOUANE
'),
	 (2168,'Prestations se rapportant au traitement des donnees et d''informations - Exportateur'),
	 (2266,'TRANSFORMATION-FABRICATION-VENTE-IMPORT/EXPORT DES PRODUITS ALIMENTAIRES, HYGIENIQUES D''ORIGINE ANIMAL ET VEGETAL.'),
	 (1970,'FABRICATION ET VENTE DE MOBILIERS, EXPORT DE PRODUITS MANUFACTURES, TOUS TRAVAUX LIES AUX BATIMENTS - EXPORTATION PRODUITS BOIS - IMPORTATEUR'),
	 (1410,'COLLECTE-TRANSFORMATION-EXPORTATION DES PRODUITS LOCAUX ET ARTISANAUX'),
	 (1958,'ACQUISITION, CONSTRUCTION, MISE EN LOCATION, VENTE DE BIENS IMMEUBLES'),
	 (866,'Couvertures d''assurances. Operations de reassurance. Placements financiers. - ');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (524,'TRANSPORT D''HYDROCARBURES ET MARCHANDISES, GARAGE, EXPORTATION, COLLECTE ET VENTES DES PRODUITS LOCAUX - Importateur'),
	 (1773,'ETUDE ET CONTROLE ROUTIER'),
	 (2095,'TRAVAUX DE BATIMENT, TRAVAUX PUBLICS ET QUINCAILLERIE'),
	 (274,'ENTREPRISE GENERALE DE CONSTRUCTION'),
	 (2228,'VENTE AU DETAIL DES CARBURANTS 
BOUTIQUE STATION SERVICE'),
	 (373,'FABRICATION DES BOUTONS FINIS ET SEMI FINIS EN MATIERES NATURELLES - EXPORTATEUR'),
	 (323,'E/SE DE CONSTRUCTION, EXPLOITATION MINIERES, IMPORT DE MSES GLES,TRANSPORT DES MARCHANDISES, OUVRAGE METALLIQUE, LOCATION ENGINS'),
	 (882,'FABRICATION ET VENTE A L''EXPORT  DE TOUS PRODUITS TEXTILES ET ACCESSOIRES - IMPORTATEUR'),
	 (2127,'IMPORTATION DE MARCHANDISES GENERALES
COMMERCE DE GROS DE MARCHANDISES GENERALES
COLLECTE ET EXPORTATION DE PRODUITS LOCAUX'),
	 (2128,'Toutes operations de negoces en matiere de materiels et materiaux de constructions - Exportateur - Importateur; vente en gros et en detail et d''une maniere generale toutes operations commerciales ou financieres, mobilieres ou imobilieres pouvant se rattacher directement ou indirectement a l''objet social precite et susceptible d''en favoriser le developpement et la realisation.');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2114,'LA PRODUCTION ET POST-PRODUCTION VIDEO.'),
	 (2588,'EXPLOITATION DE STATION SERVICE'),
	 (2700,'VENTE CARBURANTS-LUBRIFIANT-LAVAGE-ENTRETIENT - COMMERCE DE BOISSONS ALCOOLISEES'),
	 (2356,'OPERATION ET MAINTENANCE DU CENTRALE ELECTRIQUE ET DU GENERATEUR'),
	 (2697,'AGENCE DE PLACEMENT IMMOBILIER '),
	 (1700,'VENTE, INSTALLATION, DEPANNAGE DE MATIERELS ELECTRIQUES'),
	 (622,'Marchand lubrifiants, huiles et carburants - Exploitation de stations services - Vente de marchandises generales -  -  -  - Importateur'),
	 (932,'COMMERCIALISATIONS DES PRODUITS DU GROUPE - TRANSFORMATION ACHAT ET VENTE PRODUITS LAITIERS ET DERIVES AINSI QUE TOUT AUTRES PRODUITS ALIMENTAIRES, EXPORTATEUR, IMPORTATEUR'),
	 (1662,'GROSSISTE, IMPORTATEUR, REPARTITEUR EN MEDICAMENTS'),
	 (1589,'DISTRIBUTEUR  ORANGE MADAGASCAR, CYBER CAFE');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2404,'VENTE DE MARCHANDISES GENERALES ET BOISSONS ALCOOLIQUES EN GROS'),
	 (1278,'Importation,vente et maintenance des machines agricoles,materiels electroniques, Exportateur, Importateur'),
	 (1296,'STATION SERVICE: COMMERCIALISATION DE COMBUSTIBLES, LAVAGE, BOUTIQUE'),
	 (2890,'ENTREPRISES DE CONSTRUCTION,IMPORT DE MATERIAUX ET EQUIPEMENTS DE CONSTRUCTIONS'),
	 (525,'COMMERCANT GROSSISTE'),
	 (1696,'COMMERCE  EN  GROS  ET  DETAIL  DE MATERIAUX  DE CONSTRUCTION,IMPORTATEUR'),
	 (2351,'ENTREPRISES DE CONSTRUCTIONS'),
	 (201,'CONFECTION, VENTE ET EXPORTATION DE DIVERS ARTICLES D''HABILLEMENT - IMPORT-EXPORT DE TOUS PRODUITS NECESSAIRES A CES ACTIVITES'),
	 (2377,'IMPORT-EXPORT DES PRODUIT AVICOLE; AGRICOLE ET AGRO - INDUSTRIELS ET DE MATIERES PREMIERS ET ACCESSOIRES DESTINEES A L''INDUSTRIE AGRO-ALIMENTAIRE'),
	 (2738,'Revendeur de produits petroliers et derives');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (991,'IMPRESSION SERIGRAPHIQUE D''ARTICLE D''HABILLEMENT - EXPORTATEUR'),
	 (906,'Fabricant de produits chimiques - Vente en gros et details de produits chimiques - Importateur'),
	 (2889,'CONSTRUCTION, PRODUCTION, REALISATION DE BATEAUX A VOILE ET OU A MOTEUR EN MATERIAUX COMPOSITES ET OU TRADITIONNELS, ET DE TOUTES PIECES, MATERIELS, SYSTEMES, ACCASTILLAGES, ET ACCESSOIRES, ... IMPORTATIONS, COMMERCIALISATIONS, VENTES BATEAUX ET MATERIELS - Exportateur'),
	 (2051,'ACHAT ET VENTE DE PRODUIT DE BEAUTE , DE SPIRITUEUX, D''ARTICLE DE CADEAUX SUR LE PLAN LOCAL ET A L''IMPORTATION DESTINEE A LA VENTE EN DUTY FREE'),
	 (520,'COMMERCANT EN GROS ET DETAIL'),
	 (1689,'STATION SERVICE POUR VENTE AU DETAIL DE CARBURANTS, LUBRIFIANTS, BOUTIQUE.'),
	 (2891,'Importation, vente (Gros, Detail): Quincaillerie, Materiaux de Construction, Transformation de Feuilles Metalliques en differents types de toles, Importateur, Importateur, Importateur'),
	 (1341,'IMPORTATION,EXPORTATION,RECOLTE,PECHE,TRANSFORMATION DE TOUT PRODUITS'),
	 (693,'IMPORTATION, VENTE ET DISTRIBUTION DE MEUBLES ET D''APPAREILS ELECTROMENAGERS ET TOUS LES AUTRES MENTIONNES DANS LE STATUT'),
	 (743,'STATION  SERVICE');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2892,'Embouteilleur et vente en gros des boissons alcooliques - Distillerie de rhum - Vieillissement - Importateur'),
	 (651,'Revendeur de materiels Agricoles Industriels Techniques et automobiles - vente de pieces detachees au detail - Importateur'),
	 (1053,'VENTE AU DETAIL DE PRODUITS D''HYDROCARBURE ET SERVICES'),
	 (2306,'ELEVAGE ET AGRICULTURE,COLLECTE DE PRODUITS LOCAUX,TRANSFORMATION DE PRODUITS LAITIERS, Exportateur, Importateur'),
	 (2713,'Exportateur des produits locaux, Exportateur'),
	 (2093,'BUREAU D''ETUDES - EXPORTATEUR'),
	 (858,'PLACEMENT FINANCIER'),
	 (560,'IMPORTATEUR GROSSISTE DETAILLANT EN MARCHANDISES GENERALES, APPAREILS ELECTROMENAGER, BOISSONS HYGIENIQUES ,ALCOOLIQUES, COSMETIQUES.   , Importateur, Importateur'),
	 (798,'Fabrication en propre ou sous licence, l''importation, l''exportation, la distribution de tabacs a fumer, cigarettes, cigares et cigarillos'),
	 (2142,'STATION SERVICE/ VENTE CARBURANTS ET MARCHANDISES GENERALES');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (1628,'FOURNITURE DE SERVICE DE TELECOMMUNICATION'),
	 (2696,'Exploitations d''ecoles privees'),
	 (1428,'TOUTES OPERATIONS COMMERCIALES- IMPORT- EXPORT, COMMERCE DE GROS, DEMI-GROS, DETAILS,INDUSTRIELLES, FINANCIERES,MOBILIERES ET IMMOBILIERES, COMMERCE MARITIME.'),
	 (1549,'VENTES DES PRODUITS HYDROCARBURES : ESSENCE GASOIL PETROLE LUBRIFIANTS GAZ'),
	 (2893,'Plantat-,produc-,collecte,export de mat prem veget pour x- d''huiles veg,biomasse,pdts energ renovelables,recherche bota,dvlpt de nvlles sources veg de mat energ, Importateur'),
	 (1044,'VENTES AUTOS ET ENGINS MECANIQUES NEUFS, MECANICIEN GARAGISTE'),
	 (385,'Creation et exploitation de toutes industries. Exportation, importation, achat et vente de toutes matieres premieres, objets manufactures denrees alimentaires et produits divers.'),
	 (2895,'COMMISSIONAIRE EN DOUANE - TRANSPORT - TRANSIT - TRANSPORT MARITIME - AERIEN - TERRESTRE'),
	 (1460,'TRAITEMENT DE DONNEES INFORMATIQUES - EXPORTATEUR'),
	 (1299,'- TOUTES ACTIVITES HALIEUTIQUES ET EN PARTICULIER LA PECHE EN MER DE TOUS MOLLUSQUES, POISSONS OU AUTRES ESPECES, L''AFFRETEMENT ET LA CONSIGNATION DE TOUT NAVIRE;
- L''ACHAT, LA COLLECTE, LA TRANSFORMATION ET/OU LE CONDITIONNEMENT, ET/OU LA COMMERCIALISATION DESDITS PRODUITS PAR L''EXPORTATION ET LE MARCHE LOCAL;
- ET PLUS GENERALEMENT, LA PARTICIPATION SOUS UNE FORME QUELCONQUE A TOUTES ENTREPRISES COMMERCIALES, INDUSTRIELLES OU FINANCIERES, MOBILIERES OU IMMOBILIERES, AYANT L''UN DES OBJETS CI-DESSUS OU UN OBJET S''Y RATTACHANT.');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (349,'GROSSISTE PHARMACEUTIQUE - IMPORTATEUR'),
	 (2240,'BANQUE'),
	 (1598,'VENTE DE CARBURANT AU DETAIL'),
	 (465,'ETABLISSEMENT FINANCIER'),
	 (1886,'REALISATION DE PRESTATIONS DE CONTACTS  PAR TOUS MOYENS DE COMMUNICATION'),
	 (2449,'ACHAT ET VENTE DE FRUITS, TRANSFORMATION DE FRUITS, VENTE EN GROS ET AU DETAIL DE LA PRODUCTION ET EXPORTATION. - IMPORTATEUR'),
	 (3064,'production-et-vente-d-energie-electrique-generee-a-partir-de-systemes-solaires-eoliens-hydrauliques-maremoteurs-biomasses-et-thermiques-ainsi-aux-conditions-legales-et-reglementaires-en-la-matieres-ainsi-que-le-developpement-de-projets-d-efficacite-energetiques-et-d-activites-liees-au-developpement-durable-en-general.-vente-ou-location-de-systemes-cites-ci-dessus-acquisition-installation-exploitat'),
	 (3065,'la-production-et-la-vente-d-energie-solaire-aux-conditions-legales-et-reglementaires-en-la-matiere-ainsi-que-le-developpement-de-projets-d-efficacite-energetique-et-d-activites-liees-au-developpement-durable-en-general'),
	 (370,'REGULATEUR DES FREQUENCES'),
	 (898,'Commerce d''achat, de vente de ts biens de consom-,en gros et/ou detail-Mise a disposit- d''emplacemt a l''etat nu ou equipes destines a accueillir des distributeurs specialises, Importateur');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2139,'DETAILLANT DES CARBURANTS ET LUBRIFIANTS - VENTES AU DETAIL DES PIECES DETACHEES ET QUINCAILLERIE'),
	 (598,'collecte-de-lait-fabrication-commercialisat-de-produits-laitiers-alimentaires.-acquisit-exploitat-gestion-de-biens-mobiliers-et-immobiliers.-acquisit-creation-exploitat-de-toutes-marques-de-fabrique.-operations-commerciales-industrielles-mobilieres-immobilieres-financieres-importateur'),
	 (35,'ETUDE, REALISATION, ACQUISITION DE TOUTES UNITES INDUSTRIELLES OU AGRICOLES-Cce de gros et detail de marchandises generales, marchand forain en gros et detail dans tout le territoire malgache -Rizerie, collecte de Xts locaux en gros, achat et revente de Xts locaux- -Grossiste exploitant d''entrepot et stockage -Ventes de marchandises generales en gros et detail -Exportateur - Importateur-commerce de gros d''articles de quincaillerie et mat  de construct-'),
	 (2132,'- DISTRIBUTEUR ET GROSSISTE EN TELEPHONIE ORANGE
- POUR REALISER CET OBJET, LA SOCIETE POURRA FAIRE TOUTES OPERATIONS POUVANT SE RAPPORTER DIRECTEMENT OU INDIRECTEMENT, OU ETRE UTILES E L''OBJET SOCIAL OU SUSCEPTIBLES D''EN FACILITER LA REALISATION'),
	 (2038,'CONSTRUCTION IMMEUBLE - OUVRAGES: MUNICIPAUX, ELECTROMECANIQUES'),
	 (2353,'HOTELLERIE ET RESTAURATION '),
	 (1275,'REGULATEUR DU SECTEUR PETROLIER AVAL'),
	 (2452,'L achat et/ou la construction d ensembles et infrastructures destines a accueillir des equipements de telecommunication et/ou de teletransmission ; - La gestion, la maintenance et l entretien de ces infrastructures et equipements ; - La fourniture de diverses prestations d audit, conseil et etudes en matiere d ingenierie d infrastructures, de tele-communications et d energies, la location d espaces dans ces domaines ; - Toute activite liee a la gestion, l exploitation et le commerce des infrastructures et equipements de telecommunication - Importateur'),
	 (2720,'COLLECTE - EXPORT DES PRODUITS AGRICOLES - IMPORTATION ET COMMERCE DE GROS DE PPN'),
	 (3070,'commercialisation-exportation-de-produits-locaux-stockage-conditionnement-exportation-de-vanille-importation-de-marchandises-generales-et-des-materiaux-de-construction');
INSERT INTO SIGTASAD.TAX_PAYER_ACTIVITY_DESC (TAX_PAYER_NO,ACTIVITY_DESC) VALUES
	 (2399,'CENTRALE D''ACHATS D''ESPACE MEDIA ET REGIE PUBLICITAIRE'),
	 (825,'CONFECTION D''HABILLEMENT TEXTILE - EXPORTATEUR - IMPORTATEUR'),
	 (2131,'MARCHANDISES GENERALES AU DETAIL - RPRESENTANT DE COMMERCE - BOISSONS ALCOOLIQUES EN GROS ET EN DETAIL'),
	 (2407,'ACHAT VENTE EXPORTATION DES PIERRES INDUSTRIELLES ,PRECIEUSES,FINES,BRUTES ET TRAVAILLEES, DES PRODUITS ARTISANAUX
FABRICATION VENTE EXPORTATION  DES BIJOUX ET METAUX PRECIEUX OU NON
ACHAT IMPORTATION ET VENTE DES PRODUITS LAPIDAIRE ET BIJOUTERIES 
LAPIDAIRERIE DES PIERRES INDUSTRIELLES , PRECIEUSES , FINES , BIJOUX , ET METAUX PRECIEUX .
TRANSFORMATION ET TAILLE DE TOUTES SUBSTANCES MINERALES
EXPORTATION ET PROSPECTION DES GISEMENTS MINIERS.'),
	 (203,'EXTRACTION - TRANSFORMATION - EXPORTATION DE MINERAI DE CHROME - Importateur'),
	 (2054,'TRAVAUX DE CONSULTANCE');